#!/usr/bin/env bash
set -e

ln -sf /dev/stdout /var/log/nginx/access.log
ln -sf /dev/stderr /var/log/nginx/error.log

# start nginx
nginx -c $PWD/nginx.conf &

# run the FastAPI app under Gunicorn→Uvicorn
exec gunicorn \
  --bind unix:/tmp/gunicorn.sock \
  --workers ${MODEL_SERVER_WORKERS:-1} \
  --timeout ${MODEL_SERVER_TIMEOUT:-60} \
  --worker-class uvicorn.workers.UvicornWorker \
  wsgi:application
