service: file-uploader-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    BUCKET_NAME: my-s3-bucket

functions:
  uploadFile:
    handler: lambda_function.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:879961718398:layer:DVC_Lambda_Layer:1  # Reference your custom layer in the specific function
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: /upload
          method: post
          cors: true
          # If you're testing raw/binary uploads, you might also need:
          # request:
          #   contentHandling: CONVERT_TO_BINARY

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true  # This will ensure dependencies are packaged with the function.
    slim: true # Optional, to reduce the size of the deployment package.

package:
  include:
    - lambda_function.py
    - requirements.txt

